// Java view of sample-python-project/tests/test_order_service.py
// Generated by Pyrite (rules engine). Read-only reading aid: edit the Python source instead.
package sample_python_project.tests;

import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import pytest;
import inventory.models.Customer;
import inventory.models.OrderStatus;
import inventory.models.Product;
import inventory.repository.InMemoryRepository;
import inventory.services.order_service.OrderService;

public final class TestOrderService {
    @Fixture
    public static OrderService service() {
        InMemoryRepository repo = new InMemoryRepository();
        repo.add_product(new Product(/* sku = */ "A", /* name = */ "Thing", /* price = */ 10.0, /* stock = */ 5));
        repo.add_customer(new Customer(/* id = */ 1, /* name = */ "Ada", /* email = */ "ada@example.com"));
        return new OrderService(repo);
    }

    public static void test_place_order_reserves_stock(Object service) {
        var order = service.place_order(1, Map.of("A", 2));
        assert order.total() == 20.0;
        assert service.repo.product("A").stock == 3;
    }

    public static void test_empty_order_is_rejected(Object service) {
        try (var ctx = pytest.raises(IllegalArgumentException)) { // with: context manager
            service.place_order(1, new HashMap<>());
        }
    }

    public static void test_pay_changes_status(Object service) {
        var order = service.place_order(1, Map.of("A", 1));
        service.pay(order.id);
        assert order.status == OrderStatus.PAID;
    }
}
