// Java view of sample-python-project/main.py
// Generated by Pyrite (rules engine). Read-only reading aid: edit the Python source instead.
package sample_python_project;

import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import logging;
import sys;
import inventory.batch.job.OrderExportJob;
import inventory.models.Customer;
import inventory.models.OrderStatus;
import inventory.models.Product;
import inventory.repository.InMemoryRepository;
import inventory.services.order_service.OrderService;
import inventory.utils.formatting.money;
import inventory.utils.formatting.table;

/** Entry point: seeds a repository, runs a batch job and prints a report. */
public final class Main {
    static Logger logger = logging.getLogger(__name__);
    public static final String DEFAULT_CURRENCY = "EUR";

    /**
     * Populate the repository with a few products and customers.
     *
     * @param repo the repo
     */
    public static void seed(InMemoryRepository repo) {
        repo.add_product(new Product(/* sku = */ "P-100", /* name = */ "Keyboard", /* price = */ 49.90, /* stock = */ 10));
        repo.add_product(new Product(/* sku = */ "P-200", /* name = */ "Mouse", /* price = */ 19.50, /* stock = */ 0));
        repo.add_product(new Product(/* sku = */ "P-300", /* name = */ "Monitor", /* price = */ 249.00, /* stock = */ 3));
        repo.add_customer(new Customer(/* id = */ 1, /* name = */ "Ada", /* email = */ "ada@example.com"));
        repo.add_customer(new Customer(/* id = */ 2, /* name = */ "Linus", /* email = */ "linus@example.com", /* vip = */ true));
    }

    public static int run(List<String> argv) {
        logging.basicConfig(/* level = */ logging.INFO);
        InMemoryRepository repo = new InMemoryRepository();
        seed(repo);
        OrderService service = new OrderService(repo, /* currency = */ DEFAULT_CURRENCY);

        Order order = service.place_order(/* customer_id = */ 2, /* items = */ Map.of("P-100", 2, "P-300", 1));
        service.pay(order.id);
        try {
            service.place_order(/* customer_id = */ 1, /* items = */ Map.of("P-200", 1));
        } catch (IllegalArgumentException exc) {
            logger.warning("expected failure: %s", exc);
        }

        OrderExportJob job = new OrderExportJob(repo, /* chunk_size = */ 2);
        JobResult result = job.run();

        List<Object> rows = repo.orders().stream().map(o -> (o.id, o.status.name, money(o.total(), DEFAULT_CURRENCY))).toList();
        System.out.println(table(List.of("id", "status", "total"), rows));
        System.out.println("Exported " + result.written + " of " + result.read + " orders, skipped " + result.skipped);
        return result.failed == 0 ? 0 : 1;
    }

    public static void main(String[] args) {
        sys.exit(run(sys.argv.subList(1, sys.argv.size())));
    }
}
