// Java view of sample-python-project/inventory/services/order_service.py
// Generated by Pyrite (rules engine). Read-only reading aid: edit the Python source instead.
package sample_python_project.inventory.services;

import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import logging;
import typing.Dict;
import typing.Optional;
import sample_python_project.inventory.models.Order;
import sample_python_project.inventory.models.OrderLine;
import sample_python_project.inventory.models.OrderStatus;
import sample_python_project.inventory.repository.InMemoryRepository;

/** Business rules for placing and paying orders. */
public final class OrderService {
    static Logger logger = logging.getLogger(__name__);

    public static final int MAX_LINES_PER_ORDER = 20;
    public static final double FREE_SHIPPING_THRESHOLD = 100.0;

    public static class OrderService {
        public InMemoryRepository repo; // assigned as self.repo in __init__()
        public String currency; // assigned as self.currency in __init__()
        @Getter
        private int placed; // assigned as self._placed in __init__()

        public OrderService(InMemoryRepository repo, String currency /* = "EUR" */) {
            this.repo = repo;
            this.currency = currency;
            this.placed = 0;
        }

        /**
         * Create an order, reserving stock for every line.
         *
         * Raises ValueError when the basket is empty, too large, or stock is missing.
         *
         * @param customer_id the customer id
         * @param items the items
         * @param note the note
         * @return the result
         */
        public Order place_order(int customer_id, Map<String, Integer> items, String /* nullable */ note /* = null */) {
            if (!items /* falsy: null or empty */) {
                throw new IllegalArgumentException("cannot place an empty order");
            }
            if (items.size() > MAX_LINES_PER_ORDER) {
                throw new IllegalArgumentException("too many lines: " + items.size() + " > " + MAX_LINES_PER_ORDER);
            }

            Customer customer = this.repo.customer(customer_id);
            Order order = new Order(/* id = */ this.repo.next_order_id(), /* customer = */ customer, /* note = */ note);

            for (var entry : items.entrySet()) {
                String sku = entry.getKey();
                int quantity = entry.getValue();
                Product product = this.repo.product(sku);
                if (!product.in_stock()) {
                    throw new IllegalArgumentException(product.name + " is out of stock");
                }
                product.reserve(quantity);
                order.lines.add(new OrderLine(/* product = */ product, /* quantity = */ quantity, /* unit_price = */ product.price));
            }

            this.placed += 1;
            logger.info("placed %s with %d line(s)", order, order.lines.size());
            return this.repo.save_order(order);
        }

        public Order pay(int order_id) {
            Order order = this._require(order_id);
            if (order.status != OrderStatus.NEW) {
                throw new IllegalArgumentException("order " + order_id + " cannot be paid in status " + order.status.name);
            }
            order.status = OrderStatus.PAID;
            return order;
        }

        public Order cancel(int order_id, String reason /* = "" */) {
            Order order = this._require(order_id);
            if (List.of(OrderStatus.SHIPPED, OrderStatus.CANCELLED).contains(order.status)) {
                throw new IllegalArgumentException("order can no longer be cancelled");
            }
            // give the stock back
            for (OrderLine line : order.lines) {
                line.product.stock += line.quantity;
            }
            order.status = OrderStatus.CANCELLED;
            order.note = Objects.requireNonNullElse(reason, order.note);
            return order;
        }

        public double shipping_cost(Order order) {
            return order.total() >= FREE_SHIPPING_THRESHOLD ? 0.0 : 4.99;
        }

        public Map<String, Double> summary() {
            Map<String, Object> totals = this.repo.orders().stream().collect(Collectors.toMap(o -> o.id, o -> o.total()));
            List<Object> paid = totals.entrySet().stream().filter((oid, t) -> this.repo.order(oid).status == OrderStatus.PAID).map((oid, t) -> t).toList();
            return Map.of("orders", (double) (len(totals)), "revenue", Math.round((paid.stream().mapToDouble(Number::doubleValue).sum()) * 100.0) / 100.0, "average", paid ? Math.round((paid.stream().mapToDouble(Number::doubleValue).sum() / paid.size()) * 100.0) / 100.0 : 0.0);
        }

        protected Order _require(int order_id) {
            Order /* nullable */ order = this.repo.order(order_id);
            if (order == null) {
                throw new IllegalArgumentException("unknown order " + order_id);
            }
            return order;
        }

    }
}
