// Java view of sample-python-project/inventory/__init__.py
// Generated by Pyrite (rules engine). Read-only reading aid: edit the Python source instead.
package sample_python_project.inventory;

import java.util.*;
import java.util.function.*;
import java.util.stream.*;

/**
 * Inventory domain package.
 *
 * Translated from {@code sample-python-project/inventory/__init__.py}, the {@code inventory} package's __init__ module.
 */
public final class Inventory {
    static String __version__ = "0.1.0";
    static List<Object> __all__ = List.of("models", "repository", "services", "batch", "utils");
}
