// Java view of sample-python-project/inventory/models.py
// Generated by Pyrite (rules engine). Read-only reading aid: edit the Python source instead.
package sample_python_project.inventory;

import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import dataclasses.dataclass;
import dataclasses.field;
import datetime.datetime;
import enum.Enum;
import typing.Optional;

/** Domain model: products, customers and orders. */
public final class Models {
    /** Life cycle of an order. */
    public enum OrderStatus {
        NEW(1),
        PAID(2),
        SHIPPED(3),
        CANCELLED(4),
    }

    @Data
    public static class Product {
        public String sku;
        public String name;
        public double price;
        public int stock = 0;

        @Property // Python property: read as obj.in_stock, rendered as obj.in_stock()
        public boolean in_stock() {
            return this.stock > 0;
        }

        /**
         * Decrease stock, refusing to go negative.
         *
         * @param quantity the quantity
         */
        public void reserve(int quantity) {
            if (quantity <= 0) {
                throw new IllegalArgumentException("quantity must be positive, got " + quantity);
            }
            if (quantity > this.stock) {
                throw new IllegalArgumentException(
                        "not enough stock for " + this.sku + ": wanted " + quantity + ", have " + this.stock);
            }
            this.stock -= quantity;
        }
    }

    @Data
    public static class Customer {
        public int id;
        public String name;
        public String email;
        public boolean vip = false;

        public double discount_rate() {
            return this.vip ? 0.1 : 0.0;
        }
    }

    @Data
    public static class OrderLine {
        public Product product;
        public int quantity;
        public double unit_price;

        @Property // Python property: read as obj.subtotal, rendered as obj.subtotal()
        public double subtotal() {
            return Math.round((this.quantity * this.unit_price) * 100.0) / 100.0;
        }
    }

    @Data
    public static class Order {
        public int id;
        public Customer customer;
        public List<OrderLine> lines = new ArrayList<>();
        public OrderStatus status = OrderStatus.NEW;
        public LocalDateTime created_at = datetime.now() /* default_factory */;
        public String /* nullable */ note = null;

        @Property // Python property: read as obj.total, rendered as obj.total()
        public double total() {
            var gross = this.lines.stream().map(line -> line.subtotal()).mapToDouble(Number::doubleValue).sum();
            return Math.round((gross * (1 - this.customer.discount_rate())) * 100.0) / 100.0;
        }

        public Set<String> skus() {
            return this.lines.stream().map(line -> line.product.sku).collect(Collectors.toSet());
        }

        public String toString() {
            return "Order #" + this.id + " (" + this.status.name + ") for " + this.customer.name + ": "
                    + String.format("%.2f", this.total());
        }
    }

    /** Base class for domain errors. */
    public static class InventoryError extends Exception {
    }

    public static class UnknownEntityError extends InventoryError {
        public String kind; // assigned as self.kind in __init__()
        public Object key; // assigned as self.key in __init__()

        public UnknownEntityError(String kind, Object key) {
            super("unknown " + kind + ": " + key);
            this.kind = kind;
            this.key = key;
        }
    }
}
