// Java view of sample-python-project/inventory/repository.py
// Generated by Pyrite (rules engine). Read-only reading aid: edit the Python source instead.
package sample_python_project.inventory;

import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import itertools;
import threading;
import typing.Dict;
import typing.Iterable;
import typing.Iterator;
import typing.List;
import typing.Optional;
import sample_python_project.inventory.models.Customer;
import sample_python_project.inventory.models.Order;
import sample_python_project.inventory.models.OrderStatus;
import sample_python_project.inventory.models.Product;
import sample_python_project.inventory.models.UnknownEntityError;

/** A tiny in-memory repository. Real code would talk to a database. */
public final class Repository {
    /** Stores products, customers and orders in dictionaries. */
    public static class InMemoryRepository {
        private Map<String, Product> _products; // assigned as self._products in __init__()
        private Map<Integer, Customer> _customers; // assigned as self._customers in __init__()
        private Map<Integer, Order> _orders; // assigned as self._orders in __init__()
        private Object _ids; // assigned as self._ids in __init__()
        private Lock _lock; // assigned as self._lock in __init__()

        public InMemoryRepository() {
            this._products = new HashMap<>(); // Map<String, Product>
            this._customers = new HashMap<>(); // Map<Integer, Customer>
            this._orders = new HashMap<>(); // Map<Integer, Order>
            this._ids = itertools.count(1);
            this._lock = new threading.Lock();
        }

        // ---- products -------------------------------------------------------

        public void add_product(Product product) {
            this._products.put(product.sku, product);
        }

        public Product product(String sku) {
            try {
                return this._products.get(sku);
            } catch (NoSuchElementException ignored) {
                throw new UnknownEntityError("product", sku);
            }
        }

        public List<Product> products_in_stock() {
            return this._products.values().stream().filter(p -> p.in_stock()).toList();
        }

        // ---- customers ------------------------------------------------------

        public void add_customer(Customer customer) {
            this._customers.put(customer.id, customer);
        }

        public Customer customer(int customer_id) {
            var customer = this._customers.get(customer_id);
            if (customer == null) {
                throw new UnknownEntityError("customer", customer_id);
            }
            return customer;
        }

        // ---- orders ---------------------------------------------------------

        public int next_order_id() {
            synchronized (this._lock) { // with
                return this._ids.next();
            }
        }

        public Order save_order(Order order) {
            this._orders.put(order.id, order);
            return order;
        }

        public Order /* nullable */ order(int order_id) {
            return this._orders.get(order_id);
        }

        public Iterable<Order> orders(OrderStatus /* nullable */ status /* = null */) {
            for (Order order : this._orders.values()) {
                if (status == null || order.status == status) {
                    yield order; // generator
                }
            }
        }

        public Map<Integer, List<Order>> orders_by_customer() {
            Map<Integer, List<Order>> grouped = new HashMap<>();
            for (Order order : this._orders.values()) {
                grouped.computeIfAbsent(order.customer.id, key -> new ArrayList<>()).add(order);
            }
            return grouped;
        }

        public int size() {
            return this._orders.size();
        }

        public Iterator<Order> iterator() {
            return this._orders.values().iterator();
        }
    }
}
