// Java view of sample-python-project/inventory/utils/formatting.py
// Generated by Pyrite (rules engine). Read-only reading aid: edit the Python source instead.
package sample_python_project.inventory.utils;

import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import typing.Any;
import typing.Callable;
import typing.Iterable;
import typing.Sequence;

/** Small text formatting helpers. */
public final class Formatting {
    public static final Map<String, Object> SYMBOLS = Map.of("EUR", "€", "USD", "$", "GBP", "£");

    public static String money(double amount, String currency /* = "EUR" */) {
        var symbol = SYMBOLS.getOrDefault(currency, currency + " ");
        var sign = amount < 0 ? "-" : "";
        return sign + symbol + String.format("%,.2f", Math.abs(amount));
    }

    public static String pad(Object text, int width, String align /* = "left" */) {
        var s = String.valueOf(text);
        if (s.size() >= width) {
            return s.subList(0, width);
        }
        return align == "left" ? s.ljust(width) : s.rjust(width);
    }

    /**
     * Render rows as a fixed-width text table.
     *
     * @param headers the headers
     * @param rows the rows
     * @return the result
     */
    public static String table(List<String> headers, Iterable<List<Object>> rows) {
        rows = rows.stream().map(r -> r.stream().map(String::valueOf).toList()).toList();
        List<Object> widths = headers.stream().map(h -> h.size()).toList();
        for (List<Object> row : rows) {
            for (int i = 0; i < row.size(); i++) {
                Object cell = row.get(i);
                widths.put(i, Math.max(widths.get(i), cell.size()));
            }
        }
        var line = "+" + String.join("+", widths.stream().map(w -> "-".repeat((w + 2)))) + "+";
        Function<List<String>, String> render = cells -> "| "
                + String.join(" | ", Tuple.zip(cells, widths).stream().map((c, w) -> pad(c, w))) + " |";
        List<Object> out = List.of(line, render(headers), line);
        out.addAll(rows.stream().map(r -> render(r)));
        out.add(line);
        return String.join("\n", out);
    }

    /**
     * Yield successive chunks of at most `size` items.
     *
     * @param items the items
     * @param size the size
     * @return the result
     */
    public static Iterator<Object> /* generator */ chunked(List<Object> items, int size) {
        if (size <= 0) {
            throw new IllegalArgumentException("size must be positive");
        }
        for (int start = 0; start < items.size(); start += size) {
            yield items.subList(start, start + size); // generator
        }
    }

    public static String slugify(String text) {
        var cleaned = String.join("", text.trim().stream().map(ch -> ch.isalnum() ? ch.toLowerCase() : "-"));
        while (cleaned.contains("--")) {
            cleaned = cleaned.replace("--", "-");
        }
        return cleaned.strip("-");
    }
}
