// Java view of sample-python-project/inventory/batch/job.py
// Generated by Pyrite (rules engine). Read-only reading aid: edit the Python source instead.
package sample_python_project.inventory.batch;

import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import csv;
import io;
import logging;
import abc.ABC;
import abc.abstractmethod;
import dataclasses.dataclass;
import typing.Generic;
import typing.Iterator;
import typing.List;
import typing.Optional;
import typing.TypeVar;
import sample_python_project.inventory.models.Order;
import sample_python_project.inventory.models.OrderStatus;
import sample_python_project.inventory.repository.InMemoryRepository;
import sample_python_project.inventory.utils.formatting.chunked;

/**
 * A minimal chunk-oriented batch job, in the spirit of Spring Batch.
 *
 * Reader -> Processor -> Writer, processed in chunks with per-item skip handling.
 */
public final class Job {
    // type variable I = TypeVar("I")
    // type variable O = TypeVar("O")

    static Logger logger = logging.getLogger(__name__);

    public abstract static class ItemReader<I> {
        /**
         * Yield items one at a time.
         *
         * @return the result
         */
        public abstract Iterator<I> read();
    }

    public abstract static class ItemProcessor<I, O> {
        /**
         * Transform an item. Return None to filter it out.
         *
         * @param item the item
         * @return the result
         */
        public abstract O /* nullable */ process(I item);
    }

    public abstract static class ItemWriter<O> {
        public abstract void write(List<O> items);
    }

    @Data
    public static class JobResult {
        public int read = 0;
        public int written = 0;
        public int skipped = 0;
        public int failed = 0;

        @Property // Python property: read as obj.ok, rendered as obj.ok()
        public boolean ok() {
            return this.failed == 0;
        }
    }

    public static class OrderReader extends ItemReader<Order> {
        private InMemoryRepository _repo; // assigned as self._repo in __init__()
        private OrderStatus /* nullable */ _status; // assigned as self._status in __init__()

        public OrderReader(InMemoryRepository repo, OrderStatus /* nullable */ status /* = null */) {
            this._repo = repo;
            this._status = status;
        }

        public Iterator<Order> read() {
            for (var item : this._repo.orders(this._status)) { yield item; } // yield from: delegate to a sub-generator
        }
    }

    /** Flattens an order into a CSV row; cancelled orders are filtered out. */
    public static class OrderToCsvProcessor extends ItemProcessor<Order, List<String>> {
        public List<String> /* nullable */ process(Order item) {
            if (item.status == OrderStatus.CANCELLED) {
                return null;
            }
            var skus = String.join(";", item.skus().stream().sorted().toList());
            return List.of(String.valueOf(item.id), item.customer.email, item.status.name, String.format("%.2f", item.total()), skus);
        }
    }

    public static class CsvWriter extends ItemWriter<List<String>> {
        public io.StringIO /* nullable */ buffer; // assigned as self.buffer in __init__()
        private Object _writer; // assigned as self._writer in __init__()

        public static final List<Object> HEADER = List.of("id", "customer", "status", "total", "skus");

        public CsvWriter(io.StringIO /* nullable */ buffer /* = null */) {
            this.buffer = Objects.requireNonNullElse(buffer, new io.StringIO());
            this._writer = csv.writer(this.buffer);
            this._writer.writerow(this.HEADER);
        }

        public void write(List<List<String>> items) {
            for (List<String> row : items) {
                this._writer.writerow(row);
            }
        }

        public String getvalue() {
            return this.buffer.getvalue();
        }
    }

    /** Runs reader -> processor -> writer in chunks, skipping items that fail. */
    public static class ChunkedJob<I, O> {
        public ItemReader<I> reader; // assigned as self.reader in __init__()
        public ItemProcessor<I, O> processor; // assigned as self.processor in __init__()
        public ItemWriter<O> writer; // assigned as self.writer in __init__()
        public int chunk_size; // assigned as self.chunk_size in __init__()
        public int skip_limit; // assigned as self.skip_limit in __init__()

        public ChunkedJob(ItemReader<I> reader, ItemProcessor<I, O> processor, ItemWriter<O> writer, int chunk_size /* = 10 */, int skip_limit /* = 3 */) {
            this.reader = reader;
            this.processor = processor;
            this.writer = writer;
            this.chunk_size = chunk_size;
            this.skip_limit = skip_limit;
        }

        public JobResult run() {
            JobResult result = new JobResult();
            List<Object> items = new ArrayList<>(this.reader.read());
            result.read = items.size();
            for (var chunk : chunked(items, this.chunk_size)) {
                List<O> outputs = new ArrayList<>();
                for (var item : chunk) {
                    try {
                        O /* nullable */ processed = this.processor.process(item);
                    } catch (Exception exc) { // noqa: BLE001 - skip policy
                        result.skipped += 1;
                        logger.warning("skipping %r: %s", item, exc);
                        if (result.skipped > this.skip_limit) {
                            result.failed += 1;
                            throw exc; // re-raise
                        }
                        continue;
                    }
                    if (processed != null) {
                        outputs.add(processed);
                    }
                }
                if (outputs /* truthy: non-null and non-empty */) {
                    this.writer.write(outputs);
                    result.written += outputs.size();
                }
            }
            logger.info("job finished: %s", result);
            return result;
        }
    }

    public static class OrderExportJob extends ChunkedJob<Order, List<String>> {
        public CsvWriter csv; // assigned as self.csv in __init__()

        public OrderExportJob(InMemoryRepository repo, int chunk_size /* = 10 */) {
            this.csv = new CsvWriter();
            super(new OrderReader(repo), new OrderToCsvProcessor(), this.csv, /* chunk_size = */ chunk_size);
        }

        public JobResult run() {
            var result = super.run();
            logger.debug("csv output:\n%s", this.csv.getvalue());
            return result;
        }
    }
}
